// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_-UoVN99VLqiKTyt9tdMT_pxPm7gl5w',
    appId: '1:698895961636:web:011cb799be0df16ed452b1',
    messagingSenderId: '698895961636',
    projectId: 'fir-auth-app-eaab8',
    authDomain: 'fir-auth-app-eaab8.firebaseapp.com',
    storageBucket: 'fir-auth-app-eaab8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6YwlM5vJ9-nNdewPSJbPowYtvou1cTxU',
    appId: '1:698895961636:android:936dda63f983661dd452b1',
    messagingSenderId: '698895961636',
    projectId: 'fir-auth-app-eaab8',
    storageBucket: 'fir-auth-app-eaab8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_H0BbBXcTY2yHE9McqmtZ3x8bQkpEKwI',
    appId: '1:698895961636:ios:9f764055f17d3902d452b1',
    messagingSenderId: '698895961636',
    projectId: 'fir-auth-app-eaab8',
    storageBucket: 'fir-auth-app-eaab8.appspot.com',
    iosClientId: '698895961636-pu9ikea0pahbo3jvpcauor4bs2ae60og.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_H0BbBXcTY2yHE9McqmtZ3x8bQkpEKwI',
    appId: '1:698895961636:ios:732f0f8999b81e21d452b1',
    messagingSenderId: '698895961636',
    projectId: 'fir-auth-app-eaab8',
    storageBucket: 'fir-auth-app-eaab8.appspot.com',
    iosClientId: '698895961636-a8s7mnu7c752vcng8dvnmm30m4u46r62.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFirebaseAuth.RunnerTests',
  );
}
